In [1]:
#import all neccesry lib
import pandas as pd
import numpy as np

In [2]:
#import data 
df = pd.read_csv("A:\\downloads\\car_data.csv")

In [3]:
df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [4]:
#is any null value is present or not if it is present then concatenate the all null value
df["owner"].isnull().sum()

0

In [5]:
#count all the type of data present in owner column
df["owner"].value_counts()

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [6]:
 df["seller_type"].value_counts()

Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

# Encoding the data set

In [7]:
#Encode the value in column 2,3
x = df.iloc[:,[1,3,4,6]].values
y = df.iloc[:,[2]].values

In [8]:
x

array([[2007, 70000, 'Petrol', 'Manual'],
       [2007, 50000, 'Petrol', 'Manual'],
       [2012, 100000, 'Diesel', 'Manual'],
       ...,
       [2009, 83000, 'Petrol', 'Manual'],
       [2016, 90000, 'Diesel', 'Manual'],
       [2016, 40000, 'Petrol', 'Manual']], dtype=object)

In [9]:
#import labelencoder to encode the values
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
x[:,2] = lb.fit_transform(x[:,2])
lb1 = LabelEncoder()
x[:,3]=lb1.fit_transform(x[:,3])


In [10]:
x[:,2]


array([4, 4, 1, ..., 4, 1, 4], dtype=object)

# splitting the data into train test set

In [11]:
#split the all data into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)
x_train[:,:]

array([[2015, 175000, 1, 1],
       [2012, 170000, 1, 1],
       [2006, 110000, 4, 1],
       ...,
       [2016, 22000, 4, 1],
       [2015, 70000, 1, 1],
       [2013, 62000, 4, 1]], dtype=object)

In [12]:
#import randomforest to divid into predict the car price 
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=300,random_state=0)
regressor.fit(x_train,y_train)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8284\1937202092.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(x_train,y_train)


RandomForestRegressor(n_estimators=300, random_state=0)

In [21]:
# Calculate the accuracy of the model on the test data
accuracy = regressor.score(x_test, y_test)
print(accuracy * 100, "%")


75.79783473129758 %



# performing a test on given input

In [17]:
#test the data 
new_data = [2017,7000,"Petrol","Manual"]
new_data[2]=lb.transform([new_data[2]])[0]
new_data[3]=lb1.transform([new_data[3]])[0]


[2017, 7000, 4, 1]

In [18]:
#testing
print(new_data)
regressor.predict([new_data])

[2017, 7000, 4, 1]


array([617422.22222222])

In [20]:
print("the price of car",regressor.predict([new_data]))

the price of car [617422.22222222]
